---
- name: Install MySQL server
  apt:
    name: mysql-server
    state: present
  become: yes

- name: Install Python MySQL package
  apt:
    name: python3-pymysql
    state: present
  become: yes

- name: Start and enable MySQL service
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes

- name: Allow MySQL through firewall
  ufw:
    rule: allow
    port: '3306'
    proto: tcp
  become: yes

- name: Configure MySQL to allow remote connections
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
    backup: yes
  become: yes
  register: mysql_config_changed

- name: MySQL allow remote connections
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^mysqlx-bind-address'
    line: 'mysqlx-bind-address = 0.0.0.0'
    backup: yes
  become: yes
  register: mysqlx_config_changed

- name: Restart MySQL after config changes
  service:
    name: mysql
    state: restarted
  become: yes
  when: mysql_config_changed.changed or mysqlx_config_changed.changed

- name: Create MySQL database
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ database.name }}"
    state: present
  become: yes

- name: Create MySQL user
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ database.username }}"
    password: "{{ database.password }}"
    priv: "*.*:ALL"
    host: "%"
    state: present
  become: yes

- name: MySQL privileges
  mysql_query:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    query: "FLUSH PRIVILEGES"
  become: yes
